# Data-X Spring 2019: Homework 06 

## Name : Loi Chii Lek
## SID : 3034453674
## Course (IEOR 135/290) : IEOR 135

### Machine Learning



In this homework, you will do some exercises with prediction. We will cover these algorithms in class, but this is for you to have some hands on with these in scikit-learn. You can refer - https://github.com/ikhlaqsidhu/data-x/blob/master/05a-tools-predicition-titanic/titanic.ipynb

Display all your outputs.


In [1]:
import numpy as np
import pandas as pd

In [2]:
 # machine learning libraries
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import Perceptron
from sklearn.tree import DecisionTreeClassifier



__ 1. Read __`diabetesdata.csv`__ file into a pandas dataframe. 
About the data: __

1. __TimesPregnant__: Number of times pregnant 
2. __glucoseLevel__: Plasma glucose concentration a 2 hours in an oral glucose tolerance test 
3. __BP__: Diastolic blood pressure (mm Hg)  
5. __insulin__: 2-Hour serum insulin (mu U/ml) 
6. __BMI__: Body mass index (weight in kg/(height in m)^2) 
7. __pedigree__: Diabetes pedigree function 
8. __Age__: Age (years) 
9. __IsDiabetic__: 0 if not diabetic or 1 if diabetic) 








In [3]:
df = pd.read_csv("./diabetesdata.csv")
df.head()


TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  IsDiabetic
0              6         148.0  72        0  33.6     0.627  50.0           1
1              1           NaN  66        0  26.6     0.351  31.0           0
2              8         183.0  64        0  23.3     0.672   NaN           1
3              1           NaN  66       94  28.1     0.167  21.0           0
4              0         137.0  40      168  43.1     2.288  33.0           1

**2. Calculate the percentage of Null values in each column and display it. **

In [4]:
df.isnull().sum()/df.shape[0]

TimesPregnant    0.000000
glucoseLevel     0.044271
BP               0.000000
insulin          0.000000
BMI              0.000000
Pedigree         0.000000
Age              0.042969
IsDiabetic       0.000000
dtype: float64

**3. Split __`data`__  into  __`train_df`__ and __`test_df`__  with 15% as test.**


In [35]:
from sklearn.model_selection import train_test_split

X = df.iloc[:,:-1]
Y = df.iloc[:, -1]


x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.15, random_state = 10)

train_df = x_train.join(y_train)
test_df = x_test.join(y_test)
#_#

test_df.head()


TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
568              4         154.0  72      126  31.3     0.338  37.0   
620              2         112.0  86      160  38.4     0.246  28.0   
456              1         135.0  54        0  26.7     0.687  62.0   
197              3         107.0  62       48  22.9     0.678  23.0   
714              3           NaN  74        0  29.5     0.121  32.0   

     IsDiabetic  
568           0  
620           0  
456           0  
197           1  
714           0

**4. Display the means of the features in train and test sets. Replace the null values in  __`train_df`__ and __`test_df`__  with the mean of EACH feature column separately for train and test. Display head of the dataframes.**

In [37]:
x_train = x_train.fillna(x_train.mean())
x_test = x_test.fillna(x_test.mean())

## i understand what the question is asking for, 
## but isn't that going one whole round just to do a simple train test split?
## x_train, x_test, y_train, y_test = train_test_split(X.fillna(X.mean()), Y.fillna(Y.mean()), test_size=0.15, random_state = 10)

train_df = train_df.fillna(train_df.mean())
test_df = test_df.fillna(test_df.mean())

print(train_df.head())
print(test_df.head())

     TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
466              0          74.0  52       36  27.8     0.269  22.0   
280              0         146.0  70        0  37.9     0.334  28.0   
563              6          99.0  60       54  26.9     0.497  32.0   
458             10         148.0  84      237  37.6     1.001  51.0   
157              1         109.0  56      135  25.2     0.833  23.0   

     IsDiabetic  
466           0  
280           1  
563           0  
458           1  
157           0  
     TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
568              4    154.000000  72      126  31.3     0.338  37.0   
620              2    112.000000  86      160  38.4     0.246  28.0   
456              1    135.000000  54        0  26.7     0.687  62.0   
197              3    107.000000  62       48  22.9     0.678  23.0   
714              3    117.463636  74        0  29.5     0.121  32.0   

     IsDiabetic  
568           0  
62

**5. Split __`train_df`__ & __`test_df`__   into  __`X_train`__, __`Y_train`__  and __`X_test`__, __`Y_test`__. __`Y_train`__  and __`Y_test`__ should only have the column we are trying to predict,  __`IsDiabetic`__.**

In [39]:
print(x_train.head())
print(x_test.head())
print(y_train.head())
print(y_test.head())



     TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age
466              0          74.0  52       36  27.8     0.269  22.0
280              0         146.0  70        0  37.9     0.334  28.0
563              6          99.0  60       54  26.9     0.497  32.0
458             10         148.0  84      237  37.6     1.001  51.0
157              1         109.0  56      135  25.2     0.833  23.0
     TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age
568              4    154.000000  72      126  31.3     0.338  37.0
620              2    112.000000  86      160  38.4     0.246  28.0
456              1    135.000000  54        0  26.7     0.687  62.0
197              3    107.000000  62       48  22.9     0.678  23.0
714              3    117.463636  74        0  29.5     0.121  32.0
466    0
280    1
563    0
458    1
157    0
Name: IsDiabetic, dtype: int64
568    0
620    0
456    0
197    1
714    0
Name: IsDiabetic, dtype: int64


**6. Use this dataset to train perceptron, logistic regression and random forest models using 15% test split. Report training and test accuracies. Try different hyperparameter values for these models and see if you can improve your accuracies.**

In [76]:
# 6a. Logistic Regression

logreg = LogisticRegression(penalty='l1',dual=False,max_iter=110, C=1, solver='liblinear')
logreg.fit(x_train,y_train)

print('Accuracy on training set: '+str(np.round(sum(logreg.predict(x_train)==y_train)/len(y_train)*100,1))+'%')
print('Accuracy on test set: '+str(np.round(sum(logreg.predict(x_test)==y_test)/len(y_test)*100,1))+'%')



Accuracy on training set: 76.8%
Accuracy on test set: 77.6%


In [108]:
# 6b. Perceptron
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
perceptron = Perceptron(max_iter = 10000, tol=None)                                    # instantiate 
perceptron.fit(x_train, y_train)                             # fit
acc_perceptron = perceptron.score(x_test, y_test)              # predict + evalaute

print('Perceptron labeling accuracy:', str(round(acc_perceptron*100,2)),'%')


Perceptron labeling accuracy: 74.14 %


In [109]:
# 6c. Random Forest
random_forest = RandomForestClassifier(n_estimators=500)   # instantiate
random_forest.fit(x_train, y_train)                         # fit
acc_rf = random_forest.score(x_test, y_test)                  # predict + evaluate

print('K-Nearest Neighbors labeling accuracy:', str(round(acc_rf*100,2)),'%')


K-Nearest Neighbors labeling accuracy: 80.17 %


**7. For your logistic regression model - **

**a . Compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your train set and display it. Also display the predicted class for those samples from your logistic regression model trained before. **


In [118]:
logreg.predict_log_proba(x_train.head(10))

array([[-0.04004827, -3.23762709],
       [-0.64137979, -0.74774144],
       [-0.18363059, -1.7852399 ],
       [-1.66367351, -0.21003211],
       [-0.15293285, -1.95324846],
       [-0.08303751, -2.52969427],
       [-0.19513781, -1.73003207],
       [-0.80856485, -0.589683  ],
       [-0.34625608, -1.22871414],
       [-0.66828788, -0.71864025]])

In [119]:
logreg.predict(x_train.head(10))

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0], dtype=int64)

**b . Now compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your test set and display it. Also display the predicted class for those samples from your logistic regression model trained before.
 (using the model trained on the training set)**


In [120]:
logreg.predict_log_proba(x_test.head(10))

array([[-0.77541338, -0.61713729],
       [-0.21670298, -1.63562322],
       [-0.66798336, -0.7189606 ],
       [-0.13171904, -2.09222083],
       [-0.20325226, -1.69321281],
       [-0.07731179, -2.59831571],
       [-0.10092979, -2.34337068],
       [-0.43516827, -1.04172858],
       [-0.07409719, -2.63919745],
       [-0.36947838, -1.17472059]])

In [121]:
logreg.predict(x_test.head(10))

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

**c . What can you interpret from the log probabilities and the predicted classes?**



Probability values fall between 0 and 1, hence the log of it is always negative unless probability equals 1. The two coloumns are the log probabilities of IsDiabetic = 0 and IsDiabetic = 1. Looking at the leftmost coloumn, the smaller(more negative) the log probability is the more likely the person doesnt have diabetes (IsDiabetic = 0) and vice versa. 

**8. Is mean imputation is the best type of imputation (as we did in 4.) to use? Why or why not? What are some other ways to impute the data?**

Your answer here

In [ ]:
Nope, mean imputation can artificially inflate the correlation(adds bias into standard error) between the variables 
and the results despite preserving the unbiaseness of the data.

Hot deck imputation
A randomly chosen value from an individual in the sample who has similar values on other variables.

Cold deck imputation
A systematically chosen value from an individual who has similar values on other variables.

Regression imputation
The predicted value obtained by regressing the missing variable on other variables.

Stochastic regression imputation
The predicted value from a regression plus a random residual value.


## Extra Credit (2 pts) - MANDATORY for students enrolled in IEOR 290


**9.  Implement the K-Nearest Neighbours (https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm) algorithm for k=1 from scratch in python (do not use KNN from existing libraries). KNN uses Euclidean distance to find nearest neighbors. Split your dataset into test and train as before. Also fill in the null values with mean of features as done earlier. Use this algorithm to predict values for 'IsDiabetic' for your test set. Display your accuracy. **